apiVersion: v2
description: Prometheus Blackbox Exporter
name: duplo-blackbox-exporter
version: 11.5.0
appVersion: v0.27.0
sources:
  - https://github.com/prometheus/blackbox_exporter
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter
keywords:
  - prometheus
  - blackbox
  - monitoring